version: '3.5'
services:
    website_build:
        build: .
        ports:
            - '5001:5001'
    mongodb:
        image: mongo:latest
        depends_on:
            - website_build
        volumes:
            - ./mongo_db:/data/db
